# Generated by Django 4.0.5 on 2022-07-03 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='recomendation',
            field=models.CharField(choices=[('Must watch', 'Must Watch'), ('Should watch', 'Should Watch'), ('Avoid watch', 'Avoid Watch'), ('No opinion', 'No Opinion')], default='No opinion', max_length=50),
        ),
    ]
